version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "src-tauri"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      tauri:
        patterns:
          - "@tauri-apps*"
      tailwindcss:
        patterns:
          - "@tailwindcss*"
          - "tailwindcss*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
